JUDGE0_TELEMETRY_ENABLE=false
ENABLE_WAIT_RESULT=true
ENABLE_COMPILER_OPTIONS=true
ENABLE_COMMAND_LINE_ARGUMENTS=true
ENABLE_BATCHED_SUBMISSIONS=true
ENABLE_CALLBACKS=false
ENABLE_ADDITIONAL_FILES=false
USE_DOCS_AS_HOMEPAGE=true

REDIS_HOST=judge0-redis
REDIS_PORT=6379
REDIS_PASSWORD=judge0-redis-password

POSTGRES_HOST=judge0-db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0-postgres-password

CPU_TIME_LIMIT=2
MAX_CPU_TIME_LIMIT=30
CPU_EXTRA_TIME=1
WALL_TIME_LIMIT=10
MAX_WALL_TIME_LIMIT=45
MEMORY_LIMIT=128000
MAX_MEMORY_LIMIT=512000
STACK_LIMIT=64000
MAX_PROCESSES_AND_OR_THREADS=60
MAX_FILE_SIZE=1024
MAX_EXTRACT_SIZE=10240
ENABLE_NETWORK=false

RAILS_ENV=production
RAILS_MAX_THREADS=2
RAILS_SERVER_PROCESSES=2
SECRET_KEY_BASE=code-execution-service-local-judge0-secret
