"""create core platform tables

Revision ID: 20260627_0001
Revises:
Create Date: 2026-06-27 18:13:26.261452
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20260627_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

CORE_TABLES = frozenset(
    {
        "ai_run_logs",
        "assessment_questions",
        "assessment_slots",
        "assessment_templates",
        "candidate_assessments",
        "candidates",
        "question_bank_questions",
        "question_groups",
        "submissions",
        "user_roles",
    }
)


def _adopt_complete_legacy_schema() -> bool:
    """Adopt a complete pre-Alembic schema, rejecting partial installations."""

    existing_tables = set(sa.inspect(op.get_bind()).get_table_names())
    managed_tables = existing_tables & CORE_TABLES
    if not managed_tables:
        return False

    missing_tables = sorted(CORE_TABLES - existing_tables)
    if missing_tables:
        missing = ", ".join(missing_tables)
        raise RuntimeError(
            "Cannot adopt a partial legacy core schema. "
            f"Missing managed tables: {missing}"
        )
    return True


def upgrade() -> None:
    if _adopt_complete_legacy_schema():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_run_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("recruiter_uid", sa.String(length=128), nullable=False),
        sa.Column("task_name", sa.String(length=120), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("model_name", sa.String(length=120), nullable=False),
        sa.Column("schema_name", sa.String(length=120), nullable=False),
        sa.Column("workflow_mode", sa.String(length=40), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column(
            "request_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "response_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_run_logs_recruiter_uid"),
        "ai_run_logs",
        ["recruiter_uid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_run_logs_task_name"), "ai_run_logs", ["task_name"], unique=False
    )
    op.create_table(
        "assessment_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("recruiter_uid", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column(
            "duration_minutes", sa.Integer(), server_default="60", nullable=False
        ),
        sa.Column("passing_score", sa.Float(), server_default="40.0", nullable=False),
        sa.Column("test_case_score_weight", sa.Float(), nullable=False),
        sa.Column("coding_score_weight", sa.Float(), nullable=False),
        sa.Column("ai_score_weight", sa.Float(), nullable=False),
        sa.Column("allow_resume", sa.Boolean(), nullable=False),
        sa.Column("shuffle_questions", sa.Boolean(), nullable=False),
        sa.Column(
            "question_count_per_candidate",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column("show_score_to_candidate", sa.Boolean(), nullable=False),
        sa.Column("proctoring_mode", sa.String(length=30), nullable=False),
        sa.Column("hidden_feedback_mode", sa.String(length=20), nullable=False),
        sa.Column("max_hidden_checks", sa.Integer(), nullable=False),
        sa.Column("hidden_check_cooldown_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "supported_languages",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="available",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessment_templates_recruiter_uid"),
        "assessment_templates",
        ["recruiter_uid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_templates_status"),
        "assessment_templates",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_templates_title"),
        "assessment_templates",
        ["title"],
        unique=False,
    )
    op.create_table(
        "candidates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("recruiter_uid", sa.String(length=128), nullable=False),
        sa.Column("full_name", sa.String(length=180), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_candidates_email"), "candidates", ["email"], unique=False)
    op.create_index(
        op.f("ix_candidates_recruiter_uid"),
        "candidates",
        ["recruiter_uid"],
        unique=False,
    )
    op.create_table(
        "question_bank_questions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("recruiter_uid", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("problem_statement", sa.Text(), nullable=False),
        sa.Column("difficulty", sa.String(length=20), nullable=False),
        sa.Column("topics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=False),
        sa.Column("constraints", sa.Text(), nullable=False),
        sa.Column("input_format", sa.Text(), nullable=False),
        sa.Column("input_explanation", sa.Text(), nullable=False),
        sa.Column("output_format", sa.Text(), nullable=False),
        sa.Column("output_explanation", sa.Text(), nullable=False),
        sa.Column(
            "sample_test_cases", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "hidden_test_cases", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("reference_solution", sa.Text(), nullable=False),
        sa.Column("reference_language", sa.String(length=40), nullable=False),
        sa.Column(
            "supported_languages",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("candidate_solve_time_minutes", sa.Integer(), nullable=False),
        sa.Column("execution_time_limit_seconds", sa.Integer(), nullable=False),
        sa.Column("memory_limit_mb", sa.Integer(), nullable=False),
        sa.Column("metadata_status", sa.String(length=20), nullable=False),
        sa.Column("difficulty_source", sa.String(length=30), nullable=False),
        sa.Column(
            "validation_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("validation_status", sa.String(length=20), nullable=False),
        sa.Column("validation_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "reference_solutions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("solution_approach", sa.Text(), nullable=False),
        sa.Column("time_complexity", sa.String(length=160), nullable=False),
        sa.Column("space_complexity", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("creation_mode", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_bank_questions_difficulty"),
        "question_bank_questions",
        ["difficulty"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_bank_questions_recruiter_uid"),
        "question_bank_questions",
        ["recruiter_uid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_bank_questions_status"),
        "question_bank_questions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_bank_questions_title"),
        "question_bank_questions",
        ["title"],
        unique=False,
    )
    op.create_table(
        "question_groups",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("recruiter_uid", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "question_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_groups_name"), "question_groups", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_question_groups_recruiter_uid"),
        "question_groups",
        ["recruiter_uid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_groups_status"), "question_groups", ["status"], unique=False
    )
    op.create_table(
        "user_roles",
        sa.Column("uid", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(op.f("ix_user_roles_role"), "user_roles", ["role"], unique=False)
    op.create_table(
        "assessment_questions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("assessment_id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("question_order", sa.Integer(), nullable=False),
        sa.Column("marks", sa.Integer(), nullable=False),
        sa.Column("time_limit_minutes", sa.Integer(), nullable=True),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["assessment_templates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessment_questions_assessment_id"),
        "assessment_questions",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_questions_question_id"),
        "assessment_questions",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "assessment_slots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("assessment_id", sa.String(length=36), nullable=False),
        sa.Column("recruiter_uid", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("instructions_override", sa.Text(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "timezone_name",
            sa.String(length=80),
            server_default="Asia/Kolkata",
            nullable=False,
        ),
        sa.Column(
            "timezone_offset_minutes",
            sa.Integer(),
            server_default="330",
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "total_paused_seconds",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["assessment_templates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessment_slots_assessment_id"),
        "assessment_slots",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_slots_recruiter_uid"),
        "assessment_slots",
        ["recruiter_uid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_slots_status"), "assessment_slots", ["status"], unique=False
    )
    op.create_table(
        "candidate_assessments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("assessment_id", sa.String(length=36), nullable=False),
        sa.Column("slot_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("recruiter_uid", sa.String(length=128), nullable=False),
        sa.Column("invite_token_hash", sa.String(length=128), nullable=False),
        sa.Column("email_status", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("hidden_checks_used", sa.Integer(), nullable=False),
        sa.Column("current_question_order", sa.Integer(), nullable=False),
        sa.Column("invite_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "submission_tag",
            sa.String(length=60),
            server_default="",
            nullable=False,
        ),
        sa.Column("submission_message", sa.Text(), server_default="", nullable=False),
        sa.Column("last_hidden_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_score", sa.Float(), nullable=True),
        sa.Column("percentage", sa.Float(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["assessment_templates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"], ["assessment_slots.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidate_assessments_assessment_id"),
        "candidate_assessments",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_assessments_candidate_id"),
        "candidate_assessments",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_assessments_recruiter_uid"),
        "candidate_assessments",
        ["recruiter_uid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_assessments_slot_id"),
        "candidate_assessments",
        ["slot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_assessments_status"),
        "candidate_assessments",
        ["status"],
        unique=False,
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("candidate_assessment_id", sa.String(length=36), nullable=False),
        sa.Column("assessment_id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("source_language", sa.String(length=40), nullable=False),
        sa.Column("draft_code", sa.Text(), nullable=False),
        sa.Column("final_code", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "sample_run_result", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "hidden_check_result",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "final_hidden_result",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("last_saved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["assessment_templates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["candidate_assessment_id"],
            ["candidate_assessments.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "candidate_assessment_id",
            "question_id",
            name="uq_submission_candidate_assessment_question",
        ),
    )
    op.create_index(
        op.f("ix_submissions_assessment_id"),
        "submissions",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_submissions_candidate_assessment_id"),
        "submissions",
        ["candidate_assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_submissions_question_id"), "submissions", ["question_id"], unique=False
    )
    op.create_index(
        op.f("ix_submissions_status"), "submissions", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_submissions_status"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_question_id"), table_name="submissions")
    op.drop_index(
        op.f("ix_submissions_candidate_assessment_id"), table_name="submissions"
    )
    op.drop_index(op.f("ix_submissions_assessment_id"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_index(
        op.f("ix_candidate_assessments_status"), table_name="candidate_assessments"
    )
    op.drop_index(
        op.f("ix_candidate_assessments_slot_id"), table_name="candidate_assessments"
    )
    op.drop_index(
        op.f("ix_candidate_assessments_recruiter_uid"),
        table_name="candidate_assessments",
    )
    op.drop_index(
        op.f("ix_candidate_assessments_candidate_id"),
        table_name="candidate_assessments",
    )
    op.drop_index(
        op.f("ix_candidate_assessments_assessment_id"),
        table_name="candidate_assessments",
    )
    op.drop_table("candidate_assessments")
    op.drop_index(op.f("ix_assessment_slots_status"), table_name="assessment_slots")
    op.drop_index(
        op.f("ix_assessment_slots_recruiter_uid"), table_name="assessment_slots"
    )
    op.drop_index(
        op.f("ix_assessment_slots_assessment_id"), table_name="assessment_slots"
    )
    op.drop_table("assessment_slots")
    op.drop_index(
        op.f("ix_assessment_questions_question_id"), table_name="assessment_questions"
    )
    op.drop_index(
        op.f("ix_assessment_questions_assessment_id"), table_name="assessment_questions"
    )
    op.drop_table("assessment_questions")
    op.drop_index(op.f("ix_user_roles_role"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_question_groups_status"), table_name="question_groups")
    op.drop_index(
        op.f("ix_question_groups_recruiter_uid"), table_name="question_groups"
    )
    op.drop_index(op.f("ix_question_groups_name"), table_name="question_groups")
    op.drop_table("question_groups")
    op.drop_index(
        op.f("ix_question_bank_questions_title"), table_name="question_bank_questions"
    )
    op.drop_index(
        op.f("ix_question_bank_questions_status"), table_name="question_bank_questions"
    )
    op.drop_index(
        op.f("ix_question_bank_questions_recruiter_uid"),
        table_name="question_bank_questions",
    )
    op.drop_index(
        op.f("ix_question_bank_questions_difficulty"),
        table_name="question_bank_questions",
    )
    op.drop_table("question_bank_questions")
    op.drop_index(op.f("ix_candidates_recruiter_uid"), table_name="candidates")
    op.drop_index(op.f("ix_candidates_email"), table_name="candidates")
    op.drop_table("candidates")
    op.drop_index(
        op.f("ix_assessment_templates_title"), table_name="assessment_templates"
    )
    op.drop_index(
        op.f("ix_assessment_templates_status"), table_name="assessment_templates"
    )
    op.drop_index(
        op.f("ix_assessment_templates_recruiter_uid"), table_name="assessment_templates"
    )
    op.drop_table("assessment_templates")
    op.drop_index(op.f("ix_ai_run_logs_task_name"), table_name="ai_run_logs")
    op.drop_index(op.f("ix_ai_run_logs_recruiter_uid"), table_name="ai_run_logs")
    op.drop_table("ai_run_logs")
    # ### end Alembic commands ###
